<!DOCTYPE html>
<html lang="bn">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Smart Earn Bot Dashboard</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 font-sans p-6">

  <div class="max-w-lg mx-auto bg-white shadow-md rounded-lg p-6">
    <h1 class="text-2xl font-bold mb-4 text-center">Smart Earn Bot Dashboard</h1>

    <!-- ржЗржЙржЬрж╛рж░ ржЗржиржлрзЛ -->
    <div class="mb-6 p-4 bg-gray-50 rounded">
      <p>ЁЯСд ржирж╛ржо: <span id="username">Guest</span></p>
      <p>ЁЯТ░ ржкрзЯрзЗржирзНржЯ: <span id="points">0</span></p>
      <p>ЁЯФЧ рж░рзЗржлрж╛рж░рзЗрж▓ рж▓рж┐ржЩрзНржХ: <span id="referral">https://t.me/YourBot?start=ref123</span></p>
    </div>

    <!-- ржжрзИржирж┐ржХ рж░рж┐ржУрзЯрж╛рж░рзНржб -->
    <button id="dailyRewardBtn" class="w-full mb-4 bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">
      ЁЯТ░ ржжрзИржирж┐ржХ ржмрзЛржирж╛рж╕ ржХрзНрж▓рзЗржЗржо ржХрж░рзБржи
    </button>

    <!-- ржЯрж╛рж╕рзНржХ рж▓рж┐ржВржХ -->
    <a href="https://newspaper.42web.io" target="_blank" class="block w-full mb-4 bg-blue-500 hover:bg-blue-600 text-white text-center font-bold py-2 px-4 rounded">
      ЁЯУ░ ржЖржЬржХрзЗрж░ ржХрж╛ржЬ / ржЯрзНрж░рзНржпрж╛ржХ
    </a>

    <!-- ржЙржЗржержбрзНрж░рзЯрж╛рж▓ ржлрж░рзНржо -->
    <form id="withdrawForm" class="p-4 bg-gray-50 rounded">
      <label class="block mb-2 font-semibold">ржкрзЗржорзЗржирзНржЯ ржкржжрзНржзрждрж┐ ржУ ржЖржЗржбрж┐</label>
      <input type="text" id="paymentInfo" placeholder="ржмрж┐ржХрж╛рж╢, 01XXXXXXXXX" class="w-full mb-2 p-2 border rounded">
      <button type="submit" class="w-full bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded">
        ЁЯТ╕ ржЙржЗржержбрзНрж░рзЯрж╛рж▓ рж░рж┐ржХрзЛрзЯрзЗрж╕рзНржЯ
      </button>
    </form>

    <p id="message" class="mt-4 text-center text-red-500 font-semibold"></p>
  </div>

  <script>
    const pointsEl = document.getElementById('points');
    const usernameEl = document.getElementById('username');
    const referralEl = document.getElementById('referral');
    const messageEl = document.getElementById('message');

    let points = 0;

    document.getElementById('dailyRewardBtn').addEventListener('click', () => {
      points += 10;
      pointsEl.textContent = points;
      messageEl.textContent = "тЬЕ ржЖржкржирж┐ ржЖржЬржХрзЗрж░ рж░рж┐ржУрзЯрж╛рж░рзНржб ржХрзНрж▓рзЗржЗржо ржХрж░рзЗржЫрзЗржи!";
    });

    document.getElementById('withdrawForm').addEventListener('submit', (e) => {
      e.preventDefault();
      const info = document.getElementById('paymentInfo').value;
      if(info.trim() === '') {
        messageEl.textContent = "тЭМ ржкрзЗржорзЗржирзНржЯ ржЗржиржлрзЛ ржжрж┐рждрзЗ рж╣ржмрзЗред";
        return;
      }
      messageEl.textContent = `ЁЯТ╕ ржЙржЗржержбрзНрж░рзЯрж╛рж▓ рж░рж┐ржХрзЛрзЯрзЗрж╕рзНржЯ ржкрж╛ржарж╛ржирзЛ рж╣ржпрж╝рзЗржЫрзЗ: ${info}`;
    });
  </script>

</body>
</html>
